weekend-kaki/hangout/urls.py
from django.urls import path
from . import views

app_name = 'hangout'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('create/', views.create, name='create'),
    path('list/', views.list, name='list'),
    path('discover/', views.discover, name='discover'),
    path('<int:hangout_id>/detail/', views.detail, name='detail'),
    path('<int:hangout_id>/modify/', views.modify, name='modify'),
    path('<int:hangout_id>/delete/', views.delete, name='delete'),
    path('access-denied/', views.access_denied, name='access-denied'),
]

weekend-kaki/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/vote', views.vote, name='vote'),
]

weekend-kaki/weekend-kaki/urls.py
from django.contrib import admin
from django.urls import include, path
from polls import views as polls_views
from hangout import views as hangout_views
import django.contrib.auth.views as auth_views
from hangout.forms import LoginForm

urlpatterns = [
    path('', hangout_views.home, name='home'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('hangout/', include('hangout.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
]

weekend-kaki/hangout/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Hangout(models.Model):
    activity_choices = [
        ('FD', 'Food and drinks'),
        ('BP', 'Bars, pubs and clubs'),
        ('OD', 'Outdoor acitvities'),
        ('SE', 'Sports and exercises'),
        ('OT', 'Others'),
    ]

    name = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    activity_type = models.CharField(max_length=2,
                                     choices=activity_choices,
                                     )
    date = models.DateField(default=timezone.now)
    time = models.TimeField(default=timezone.now)
    description = models.TextField(null=True,
                                   blank=True,
                                   default='Add a description')
    owner = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='owned_hangouts',
                              default=0)
    participants = models.ManyToManyField(User,
                                          related_name='participating_hangouts')

    def __str__(self):
        return self.name

weekend-kaki/hangout/forms.py
import unicodedata

from django import forms
from .models import Hangout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class HangoutViewForm(forms.ModelForm):
    class Meta:
        model = Hangout
        fields = '__all__'
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control',
                                                  'readonly': True}),
                   'location': forms.TextInput(attrs={'class': 'form-control',
                                                      'readonly': True}),
                   'date': forms.DateInput(attrs={'class': 'form-control',
                                                  'placeholder': 'DD/MM/YYYY'}),
                   'description': forms.Textarea(attrs={'class': 'form-control',
                                                        'rows': 3,
                                                        'readonly': True}),
                   'owner': forms.Select(attrs={'disabled': True}),
                   'participants': forms.SelectMultiple(attrs={'disabled': True})}


class HangoutModifyForm(forms.ModelForm):
    class Meta:
        model = Hangout
        exclude = ['owner']


class HangoutCreateForm(forms.ModelForm):
    class Meta:
        model = Hangout
        fields = '__all__'
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
                   'location': forms.TextInput(attrs={'class': 'form-control'}),
                   'date': forms.DateInput(attrs={'class': 'form-control'}),
                   'description': forms.Textarea(attrs={'class': 'form-control',
                                                        'rows': 3}),
                   'owner': forms.HiddenInput(),
                   'participants': forms.SelectMultiple(attrs={'class': 'ui fluid search dropdown'})
                   }


class UsernameField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize('NFKC', super().to_python(value))

    def widget_attrs(self, widget):
        return {
            **super().widget_attrs(widget),
            'autocapitalize': 'none',
            'autocomplete': 'username',
        }


class LoginForm(AuthenticationForm):
    username = UsernameField(
                widget=forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Username',
                                               'autofocus': True},
                       )
    )

    password = forms.CharField(
                label='Password',
                strip=False,
                widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',
                                                  'class': 'form-control',
                                                  'placeholder': 'Password'})
    )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

weekend-kaki/hangout/views.py
from django.http.response import HttpResponseRedirect, HttpResponseRedirectBase
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone
from .models import Hangout
from .forms import HangoutViewForm, HangoutModifyForm, HangoutCreateForm
from django.urls import reverse


def home(request):
    context = {}
    return render(request, 'hangout/home.html', context)


@login_required
def profile(request):
    context = {}
    return render(request, 'hangout/profile.html', context)


@login_required
def create(request):
    if request.method == 'GET':
        form = HangoutCreateForm()
        context = {'form': form}
        return render(request, 'hangout/create.html', context)
    else:
        print(request.POST)
        input = request.POST.copy()
        input['owner'] = request.user.id
        form = HangoutCreateForm(input)
        form.save()
        return HttpResponseRedirect(reverse('hangout:list'))


@login_required
def list(request):
    owned_hangouts = request.user.owned_hangouts.filter(date__gte=timezone.now())
    participating_hangouts = request.user.participating_hangouts.filter(date__gte=timezone.now())
    past_hangouts = request.user.owned_hangouts.filter(date__lt=timezone.now())
    past_hangouts.union(request.user.participating_hangouts.filter(date__lt=timezone.now()))
    context = {'owned_hangouts': owned_hangouts,
               'participating_hangouts': participating_hangouts,
               'past_hangouts': past_hangouts,
               }
    return render(request, 'hangout/list.html', context)


@login_required
def discover(request):
    hangout_list = Hangout.objects.filter(date__gte=timezone.now())
    context = {'hangout_list': hangout_list}
    return render(request, 'hangout/discover.html', context)


@login_required
def detail(request, hangout_id):
    h = Hangout.objects.get(pk=hangout_id)
    form = HangoutViewForm(instance=h)

    if 'msg' in request.GET:
        msg = request.GET['msg']
    else:
        msg = None

    if h.owner_id == request.user.id:
        can_modify = True
    else:
        can_modify = False

    if h.date < timezone.now().date():
        can_modify = False

    context = {'hangout_id': hangout_id,
               'form': form,
               'msg': msg,
               'can_modify': can_modify,
               }
    return render(request, 'hangout/detail.html', context)


@login_required
def modify(request, hangout_id):
    h = Hangout.objects.get(pk=hangout_id)
    if h.owner_id == request.user.id:
        form = HangoutModifyForm(instance=h)
        context = {'hangout_id': hangout_id,
                   'form': form,
                   }
        if request.method == 'GET':
            return render(request, 'hangout/modify.html', context)
        else:
            form = HangoutModifyForm(request.POST, instance=h)
            form.save()
            return HttpResponseRedirect(reverse('hangout:detail', args=(hangout_id,))
                                        + '?msg=success')
    else:
        return redirect('hangout:access-denied')


@login_required
def delete(request, hangout_id):
    h = Hangout.objects.get(pk=hangout_id)
    if h.owner_id == request.user.id:
        h.delete()
        context = {}
        return render(request, 'hangout/delete.html', context)
    else:
        return redirect('hangout:access-denied')


def access_denied(request):
    return render(request, 'hangout/access_denied.html', {})

weekend-kaki/polls/views.py
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latestQuestionList'

    def get_queryset(self):
        return Question.objects.filter(pubDate__lte=timezone.now()
                                       ).order_by('-pubDate')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pubDate__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        return Question.objects.filter(pubDate__lte=timezone.now())


def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question,
                      'errorMessage': 'An error has occured!'})
    else:
        choice.votes += 1
        choice.save()
        return HttpResponseRedirect(reverse('polls:results',
                                            args=(pk,)))

weekend-kaki/hangout/templates/hangout/access_denied.html
{% extends 'hangout/base.html' %}
{% block content %}
<h1>You do not have access to this site.</h1>
<a href="{% url 'home' %}">Return to home page</a>
{% endblock %}

weekend-kaki/hangout/templates/hangout/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Semantic-UI dropdown -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/components/dropdown.min.css" integrity="sha256-uJcWG4z2GKiVmddxuVaioBQqds/UAfBKpuMlw2Xmc7Y=" crossorigin="anonymous">

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/components/transition.min.css" integrity="sha256-Hj1yjp4fXn19k1azEVKT0aEvgUWt/HlVBO6xnhidiUs=" crossorigin="anonymous">

        <!-- Date picker -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
        
        <!--  Bootstrap4  -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        
        {% load static %}
        <link rel="stylesheet" href="{% static 'hangout/style.css' %}">

        <!--  jQuery -->
        <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

        <!-- Bootstrap Date-Picker Plugin -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
        
        <!-- Semantic-UI Plugin -->
        <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/components/dropdown.min.js" integrity="sha256-uEocYy6a0MpPLLHtYV7QAGdOeMRwE0Am2WtnOg/hBfM=" crossorigin="anonymous"></script>

		<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/components/transition.min.js" integrity="sha256-k30cmb6hiQ/LGKpX2AcllUduUJ0kA4DKKStgUxkGQzM=" crossorigin="anonymous"></script>

        <nav>
            <ul class="nav-bar">
                <li id="logo-item"><img class="logo" src="{% static 'hangout/logo.png' %}"></li
                ><li><a href="{% url 'home' %}">Home</a></li
                ><li><a href="{% url 'hangout:create' %}">Create Hangout</a></li
                ><li><a href="{% url 'hangout:list' %}">My Hangouts</a></li
                ><li><a href="{% url 'hangout:discover' %}">Discover</a></li
                ><li><a href="{% url 'hangout:profile' %}">My Profile</a></li
                ><li class="login-area">{% block login %}
                    {% if user.is_authenticated %}
                    <p id="user-fullname">{{ user.get_full_name }}</p>
                    <a id="login-button" href="{% url 'logout' %}">LOG OUT</a>
                    {% else %}
                    <a id="login-button" href="{% url 'login' %}">LOG IN</a>
                    {% endif %}
                    {% endblock %}                
            </ul>
        </nav>
    </head>
    <body>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    </body>
</html>

weekend-kaki/hangout/templates/hangout/create.html
{% extends 'hangout/base.html' %}
{% block content %}

<h1>Create a Hangout</h1>
<div class="container mb-3">
<form method="post" action="{% url 'hangout:create' %}">
{% csrf_token %}
  {% for field in form.visible_fields %}
  <div class="mb-3" style="width: 50%;">
    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
    {{ field }}
  </div>
  {% endfor %}
<input type="submit" value="Create">
</form>
</div>

<script>
    $(document).ready(function(){
      var date_input=$('input[name="date"]'); //our date input has the name "date"
      // var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
      var options={
        format: 'yyyy-mm-dd',
        // container: container,
        todayHighlight: true,
        autoclose: true,
      };
      date_input.datepicker(options);
    })
</script>
<script>
  $('#id_participants')
      .dropdown()
  ;
</script>
{% endblock %}

weekend-kaki/hangout/templates/hangout/delete.html
{% extends 'hangout/base.html' %}
{% block content %}
<h1>Delete page</h1>
<p>You have successfully deleted the Hangout.</p>
<a href="{% url 'home' %}">Return to home page.</a>
{% endblock %}

weekend-kaki/hangout/templates/hangout/detail.html
{% extends 'hangout/base.html' %}
{% block content %}
<h1>{{ form.name.value }}'s Hangout details</h1>
{% if msg %}
<p class="message">Hangout saved successfully!</p>
{% endif %}
<div class="container" style="width: 50%;">
    {% for field in form %}
    <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
        {{ field }}
    </div>
    {% endfor %}
</div>


{% if can_modify %}
<div>
    <a href="{% url 'hangout:modify' hangout_id %}">Modify</a>
    <a href="{% url 'hangout:delete' hangout_id %}" 
       onclick="return confirm('Do you really want to delete this Hangout?');">Delete</a>
</div>
{% endif %}
{% endblock %}

weekend-kaki/hangout/templates/hangout/discover.html
{% extends 'hangout/base.html' %}
{% block content %}
<h1>Discover Hangouts happening</h1>
<ul>
    {% for hangout in hangout_list %}
    <li><a href="{% url 'hangout:detail' hangout.id %}">{{ hangout }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

weekend-kaki/hangout/templates/hangout/home.html
{% extends 'hangout/base.html' %}
{% block content %}
        <div class="main-content">
            <div class="welcome-message">
                <p>Welcome to Weekend Kaki!</p>
                <p class="welcome-subtext"><b>Weekend Kaki</b> is a platform for you to plan the next outing with your kakis.</p>
            </div>
            <div class="body-container">
                <div class="guide-container">
                    {% load static %}
                    <img id="hangout-img" src="{% static 'hangout/create-hangout-guide.jpg' %}">
                    <p class="guide-heading">Create Hangout</p>
                    <p class="guide">Head over to <a href="{% url 'hangout:create' %}">Create Hangout</a> to start planning with just a few clicks.</p>
                </div>
                <br>
                <div class="guide-container">
                    <img id="discover-img" src="{% static 'hangout/discover-hangout-guide.jpg' %}">
                    <p class="guide-heading">Discover Hangout</p>
                    <p class="guide">If you don't know yet what to do or where to go for your next meet-up,
                        try out <a href="{% url 'hangout:discover' %}">Discover</a> to see what your friends or people near you are planning.</p>
                </div>
            </div>
        </div>
{% endblock %}

weekend-kaki/hangout/templates/hangout/list.html
{% extends 'hangout/base.html' %}
{% block content %}
<h1>Upcoming Hangouts</h1>
<h2>Hangouts created by you</h2>
<ul>
    {% for hangout in owned_hangouts %}
    <li><a href="{% url 'hangout:detail' hangout.id %}">{{ hangout }}</a></li>
    {% endfor %}
</ul>
<h2>Hangouts you are invited to</h2>
<ul>
    {% for hangout in participating_hangouts %}
    <li><a href="{% url 'hangout:detail' hangout.id %}">{{ hangout }}</a></li>
    {% endfor %}
</ul>
<h1>Past Hangouts</h1>
<ul>
    {% for hangout in past_hangouts %}
    <li><a href="{% url 'hangout:detail' hangout.id %}">{{ hangout }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

weekend-kaki/hangout/templates/hangout/modify.html
{% extends 'hangout/base.html' %}
{% block content %}
<h1>Modify page</h1>
<form method="post" action="{% url 'hangout:modify' hangout_id %}">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="Save">
</form>


{% endblock %}

weekend-kaki/hangout/templates/hangout/profile.html
{% extends 'hangout/base.html' %}
{% block content %}
    <h1>User Profile</h1>
    <div>
        <table>
            <tr>
                <td>Full name:</td>
                <td>{{ request.user.get_full_name }}</td>
            </tr>
            <tr>
                <td>Account name:</td>
                <td>{{ request.user.get_username }}</td>
            </tr>
            <tr>
                <td>Email:</td>
                <td>{{ request.user.email }}</td>
            </tr>
            <tr>
                <td>Date joined:</td>
                <td>{{ request.user.date_joined }}</td>
            </tr>
            <tr>
                <td>Last login:</td>
                <td>{{ request.user.last_login }}</td>
            </tr>
        </table>
    </div>
{% endblock %}